### ISSUE TITLE
此扩展使用的一个「坑」

### ISSUE THREAD

**Issue by ahu** [Iamtong/laravel-admin-login-check-safe#1]
1.  最大的一个是，laravel-admin 版本至少应为1.7.3  ——但本项目 composer.json 中是 1.6 我一个基于1.5的老项目折腾了好久才发现必须升级到1.7.3之后的版本才行
2. 第二个，引用的 Carbon组件的diffForHumans方法，由于我的 Carbon 组件版本较旧，会报错DateTime::__construct() expects parameter 1 to be string, array given错误，将diffForHumans(['parts'=>2])改为diffForHumans()可以缓解。奇怪的是，按 composer 的提示升级 Carbon 到版本 2 之后，diffForHumans(['parts'=>2])依旧报错

最后十分感谢@Iamtong 开发并分享了此插件！！！强烈感谢！！！

对于需要符合国家等级保护制度安全要求的后台来说，真的是太有用了！！！强烈建议将此扩展提交到 laravel-admin 官方扩展库网站！！！我好不容易搜到的...虽然在如上问题上花了一天时间，但是节省了好几天开发时间！！！

**Comment by ahu** [comment]
我不死心，我安装 Carbon 官方指引再次升级到了最新的2.27.0版本。这次问题二终于消失了！

所以总结一下就是，@lamtong 老大只需修改一下 laravel-admin 的依赖版本即可。再次感谢！

**Comment by Iamtong** [comment]
最近一直很忙，这个东西是自己项目用的，所以没有考虑太多其他版本的兼容性，所以也没费心去提交到官方，后面有空我会继续优化的。感谢支持

**Comment by Iamtong** [comment]
> 我不死心，我安装 Carbon 官方指引再次升级到了最新的2.27.0版本。这次问题二终于消失了！
> 
> 所以总结一下就是，@lamtong 老大只需修改一下 laravel-admin 的依赖版本即可。再次感谢！

能用了就好，最近一直很忙，这个东西是自己项目用的，所以没有考虑太多其他版本的兼容性，所以也没费心去提交到官方，后面有空我会继续优化的。感谢支持
