### ISSUE TITLE
你好,请问下可以支持laravel6么,laravel6无法安装哦

### ISSUE THREAD

**Issue by uniteweiwei** [Iamtong/laravel-admin-login-check-safe#2]
` Problem 1
    - Conclusion: don't install iamtong/laravel-admin-login-check-safe 1.0.3
    - Conclusion: remove laravel/framework v6.18.3`

**Comment by uniteweiwei** [comment]
老哥,咋样了啊?

**Comment by Iamtong** [comment]
> 老哥,咋样了啊?
这周我抽空处理下

**Comment by uniteweiwei** [comment]
嗯嗯,谢谢你

**Comment by Iamtong** [comment]
已处理新版本 1.0.4可以了

**Comment by uniteweiwei** [comment]
嗯嗯..已经可以安装了,谢谢你
